// 100 reveal-screen hint phrases, generated by a 10-voice cohort (Iris,
// Cyan, Ochre, Crimson, Indigo, Spectra, Umber, Amber, Vermillion, Magenta)
// and consolidated by reviewer Pigment. Each round picks one at random.
//
// Style: 3–7 words, no trailing punctuation, "colour" spelling. Sentence
// case OR all lowercase per the voice that wrote it.

export const REVEAL_PHRASES: readonly string[] = [
  // Iris — mystic / oracular
  'Let this hue find its name in you',
  'Hold what the eye cannot explain',
  'The shade knows it is being kept',
  'Drink it in before the veil drops',
  'Press this light into your interior',
  'Receive what has been shown to you',
  'Something ancient is wearing this colour',
  'Mark it the way prophets mark stars',
  'Let the unseen leave its residue',
  'This colour is a door — enter',

  // Cyan — hypnotist
  'Let it settle behind your eyes',
  'Sink into the hue',
  'Breathe it in slowly',
  'Hold this colour close',
  'Stay with what you see',
  'Let the shade find you',
  'Absorb it, soft and still',
  'Dwell here a moment',
  'Rest your gaze on this',
  'Draw it deep inside',

  // Ochre — curator
  'Trace the light before it moves',
  'Hold the weight of this light',
  'Where does it sit in the room',
  'Let it steep before you name it',
  'Feel how far it leans from grey',
  'Take it in without a word',
  'Notice what warmth it carries',
  'Let the hue reach back first',
  'Stay until you feel its temperature',
  'Press this into the memory',

  // Crimson — coach
  'Lock this colour into you',
  'Burn it behind your eyes',
  "Hold the hue, don't drift",
  'Claim every shade of it',
  'Get it. All of it',
  'Commit this to the bone',
  'Grip the tone before it fades',
  'Take it in, take it home',
  'Sit with it. Own it',
  'Burn it in, then move',

  // Indigo — poet
  'the colour of October rain',
  'hold this until it fades',
  'light before a door closes',
  'ash settling on still water',
  'the hour the sky forgets blue',
  'breathe it into memory',
  'smoke the lantern left behind',
  'this shade of almost-evening',
  'what dusk remembers of noon',
  'let it leave its mark',

  // Spectra — scientist
  'Register the wavelength now',
  'Calibrate your internal sample',
  'Log this band before it fades',
  'Encode the hue, then release',
  'Fix the value in your record',
  'Let the spectrum settle in',
  'Sample this light precisely once',
  'Hold the frequency, then trust',
  'Fix this reading, then release',
  'Absorb the visible band fully',

  // Umber — detective
  'Commit every shade to memory',
  'Study the suspect before it vanishes',
  'Note the evidence while light holds',
  'File this colour — no second look',
  'Lock the witness in your mind',
  'Sketch the mark before it fades',
  'Read the scene, hold the hue',
  'What bleeds here, remember it',
  'The colour has an alibi — find it',
  'Name this before the light shifts',

  // Amber — bartender
  'hold on to this one',
  "we'll need this later",
  'let it land a moment',
  'keep this one close',
  'take a good look',
  "tuck it somewhere you'll find it",
  "don't let this one slip",
  'study it like a secret',
  "this colour's asking to stay",
  'carry this one with you',

  // Vermillion — old sage
  'Let this colour find its home',
  'Hold it, let the quiet in',
  'The hue knows your name',
  'Take the long way back',
  'Something this quiet stays',
  'Give it shelter in you',
  'Belong to this for now',
  'The colour will return to you',
  'Let it settle, then remember',
  "Name it when you're ready",

  // Magenta — modern / playful-tasteful
  'let it land on you',
  'stay here just a moment',
  'sit with it a second',
  'this colour is yours now',
  'absorb it like a slow breath',
  'drink it in, then we go',
  'find it somewhere inside you',
  'no skipping, just looking',
  'the shade belongs to you now',
  'let your eyes go soft',
];

export function pickRevealPhrase(): string {
  return REVEAL_PHRASES[Math.floor(Math.random() * REVEAL_PHRASES.length)];
}
