// 100 reveal-screen hint phrases, originally generated by a 10-voice cohort
// and consolidated by reviewer Pigment. Several voices were toned down in a
// follow-up pass — the mystic ("veil drops", "ancient is wearing this colour"),
// noir ("what bleeds here", "the colour has an alibi"), melancholy poet
// ("ash settling on still water", "smoke the lantern left behind"), and
// mystical sage ("the hue knows your name") strains were replaced with
// warmer, more direct lines while preserving the voice variety.
//
// Style: 3–7 words, no trailing punctuation, "colour" spelling. Sentence
// case OR all lowercase per the voice that wrote it.

export const REVEAL_PHRASES: readonly string[] = [
  // Thoughtful (was Iris)
  'Let this colour find its name',
  "Trust what you're seeing",
  'Hold this shade with care',
  'Take it in, slowly',
  'Look closely, then remember',
  'Give this colour your attention',
  'Look at this with fresh eyes',
  'Mark this colour, hold it well',
  'Notice what stays with you',
  'Step into this and stay awhile',

  // Quiet (Cyan)
  'Let it settle behind your eyes',
  'Sink into the hue',
  'Breathe it in slowly',
  'Hold this colour close',
  'Stay with what you see',
  'Let the shade find you',
  'Absorb it, soft and still',
  'Dwell here a moment',
  'Rest your gaze on this',
  'Draw it deeper in',

  // Observer (Ochre)
  'Trace the light before it moves',
  'Hold the weight of this light',
  'Where does it sit in the room',
  'Let it steep before you name it',
  'Feel how far it leans from grey',
  'Take it in without a word',
  'Notice what warmth it carries',
  'Let the hue settle first',
  'Stay until you feel its temperature',
  'Press this into memory',

  // Coach (Crimson, softened)
  'Lock this colour in',
  'Hold it behind your eyes',
  "Hold the hue, don't drift",
  'Claim every shade of it',
  'Get it. All of it',
  'Commit this to memory',
  'Grip the tone before it fades',
  'Take it in, take it home',
  'Sit with it. Own it',
  'Lock it in, then move',

  // Lyrical (Indigo, warmer)
  'the colour of early light',
  'hold this until it fades',
  'light through an open window',
  'leaves drifting in still water',
  'the hour just before sunset',
  'breathe it into memory',
  'light from a quiet window',
  'this shade of almost-evening',
  'what evening remembers of day',
  'let it leave its mark',

  // Precise (Spectra)
  'Register the wavelength now',
  'Calibrate your internal sample',
  'Log this band before it fades',
  'Encode the hue, then release',
  'Fix the value in your record',
  'Let the spectrum settle in',
  'Sample this light precisely once',
  'Hold the frequency, then trust',
  'Fix this reading, then release',
  'Absorb the visible band fully',

  // Attentive (was Umber, noir dropped)
  'Commit every shade to memory',
  'Study this colour before it fades',
  'Note the details while you can',
  'File this colour away carefully',
  'Lock this in your mind',
  'Sketch the mark before it fades',
  'Read the scene, hold the hue',
  'What you see here, remember',
  'Find what makes this colour itself',
  'Name this before the light shifts',

  // Warm (Amber)
  'hold on to this one',
  "we'll need this later",
  'let it land a moment',
  'keep this one close',
  'take a good look',
  "tuck it somewhere you'll find it",
  "don't let this one slip",
  'study it like a secret',
  "this colour's asking to stay",
  'carry this one with you',

  // Wise (was Vermillion, mystical dropped)
  'Let this colour find its home',
  'Hold it, let the quiet in',
  'The colour is yours to keep',
  'Take your time with this',
  'Something this quiet stays',
  'Give it room in your memory',
  'Stay with this for now',
  "You'll want this one later",
  'Let it settle, then remember',
  "Name it when you're ready",

  // Modern (Magenta)
  'let it land on you',
  'stay here just a moment',
  'sit with it a second',
  'this colour is yours now',
  'absorb it like a slow breath',
  'drink it in, then we go',
  'find it somewhere inside you',
  'no skipping, just looking',
  'the shade belongs to you now',
  'let your eyes go soft',
];

export function pickRevealPhrase(): string {
  return REVEAL_PHRASES[Math.floor(Math.random() * REVEAL_PHRASES.length)];
}
